---
- hosts: master
  remote_user: fonepay
  tasks:

    - name: Create domain for client with portbase 3000
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin create-domain --portbase 3000 --user admin --passwordfile glassfish4/password client 

    - name: Enable secure login for client
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin start-domain client && glassfish4/bin/asadmin --user admin --passwordfile glassfish4/password --host localhost --port 3048 enable-secure-admin
    
    - name: Add connection pool to client domain
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin start-domain client && glassfish4/bin/asadmin create-jdbc-connection-pool --user admin --passwordfile glassfish4/password --port 3048 --datasourceclassname com.mysql.jdbc.jdbc2.optional.MysqlDataSource --restype javax.sql.DataSource --property UserName=root:Port=3306:Password=f1s0ft@123:DatabaseName=FONEPAY_UAT:ServerName=10.13.194.238 merchant-admin-pool

    - name: Add connection pool to client domain
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin start-domain client && glassfish4/bin/asadmin create-jdbc-connection-pool --user admin --passwordfile glassfish4/password --port 3048 --datasourceclassname com.mysql.jdbc.jdbc2.optional.MysqlDataSource --restype javax.sql.DataSource --property UserName=ibank:Port=3306:Password=ibank:DatabaseName=CONVERGENT_UAT:ServerName=10.13.194.238 jdbc/convergentDb
    
    - name: Add resource for client-reconsile to client domain
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin start-domain client && glassfish4/bin/asadmin create-jdbc-resource --port 3048 --user admin --passwordfile glassfish4/password --connectionpoolid jdbc/convergentDb client-reconcile

    - name: Add resource for merchant-site-admin to client domain
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin start-domain client && glassfish4/bin/asadmin create-jdbc-resource --port 3048 --user admin --passwordfile glassfish4/password --connectionpoolid merchant-admin-pool merchant-site-admin

    - name: Add slave-convergent to client domain
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin start-domain client && glassfish4/bin/asadmin create-jdbc-resource --port 3048 --user admin --passwordfile glassfish4/password --connectionpoolid jdbc/convergentDb slave-convergent

    - name: Add jdbc/convergent resource pool to client domain
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin start-domain client && glassfish4/bin/asadmin create-jdbc-resource --port 3048 --user admin --passwordfile glassfish4/password --connectionpoolid jdbc/convergentDb jdbc/convergent
    
    - name: Add fonepayMerchant to client domain
      become_user: fonepay
      shell: . /home/fonepay/.bash_profile && glassfish4/bin/asadmin start-domain client && glassfish4/bin/asadmin create-jdbc-resource --port 3048 --user admin --passwordfile glassfish4/password --connectionpoolid merchant-admin-pool fonepayMerchant